name: initiate aml pipeline triggered by repo merge change

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group="rg-dev-mlops"
        az configure --defaults workspace="mlw-dev-mlops"
    - name: Create pipeline in Azure ML workspace
      run: |  
        cd src
        az ml job create -f job.yml 
        